import {
  Home,
  Store,
  ListOrdered,
  Car,
  Star,
  Tag,
  Calendar,
  Film,
  Bot,
  Map,
  Info,
  Search,
  Bell,
  MessageSquare,
  BarChart,
  Package,
  Clapperboard,
  DollarSign,
  Users,
  LineChart,
  Activity,
  Timer,
  Key,
  CreditCard,
  User,
} from "lucide-react";

export const CUSTOMER_NAV = [
    { to: "/dashboard", label: "Dashboard", icon: Home },
    { to: "/mall", label: "Browse Stores", icon: Store },
    { to: "/queue", label: "Queue", icon: ListOrdered },
    { to: "/parking", label: "Parking", icon: Car },
    { to: "/loyalty", label: "Loyalty", icon: Star },
    { to: "/offers", label: "Offers", icon: Tag },
    { to: "/events", label: "Events", icon: Calendar },
    { to: "/movies", label: "Cinema", icon: Film },
    { to: "/ai-concierge", label: "AI Concierge", icon: Bot },
    { to: "/map", label: "Mall Map", icon: Map },
    { to: "/services", label: "Services", icon: Info },
    { to: "/lost-found", label: "Lost & Found", icon: Search },
    { to: "/notifications", label: "Notifications", icon: Bell },
    { to: "/complaints", label: "Complaints", icon: MessageSquare },
];
export const ADMIN_NAV = [
    { to: "/admin", label: "Dashboard", icon: BarChart },
    { to: "/admin/stores", label: "Stores", icon: Store },
    { to: "/admin/products", label: "Products", icon: Package },
    { to: "/admin/offers", label: "Offers", icon: Tag },
    { to: "/admin/bookings", label: "Movie Bookings", icon: Clapperboard },
    { to: "/admin/lost-reports", label: "Lost Reports", icon: Package },
    { to: "/admin/sales", label: "Sales", icon: DollarSign },
    { to: "/admin/queue", label: "Queue Monitor", icon: ListOrdered },
    { to: "/admin/customers", label: "Customer Insights", icon: Users },
];
export const SUPER_ADMIN_NAV = [
    { to: "/super-admin", label: "Dashboard", icon: BarChart },
    { to: "/super-admin/analytics", label: "Analytics", icon: LineChart },
    { to: "/super-admin/crowd", label: "Crowd Traffic", icon: Activity },
    { to: "/super-admin/queues", label: "Queue Efficiency", icon: Timer },
    { to: "/super-admin/parking", label: "Parking", icon: Car },
    { to: "/super-admin/stores", label: "Stores", icon: Store },
    { to: "/super-admin/users", label: "Users & Roles", icon: Key },
    { to: "/super-admin/complaints", label: "Complaints", icon: MessageSquare },
    { to: "/super-admin/admins", label: "Admins", icon: User },
    { to: "/super-admin/tenants", label: "Tenants & Billing", icon: CreditCard },
];
